version: '3.5'
services:
  app:
    container_name: rythm_api
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/rythm_api
      - SESSION_SECRET=${SESSION_SECRET}
      - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    links:
      - mongo
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - /data/rythm_api-data:/data/db
    ports:
      - "27017:27017"
